version: '3.8'

services:
  backend:
    image: my-backend
    build:
      context: ./file-editor/backend
    ports:
      - "8000:8000"
    volumes:
      - ${TEMPLATE_DIR:-./template}:/app/template
    environment:
      - ROOT_PATH=/app/template

  frontend:
    image: my-frontend
    build:
      context: ./file-editor/frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
