version: '3.8'

services:
  backend:
    image: my-backend
    build:
      context: ./file-editor/backend
    user: "${UID:-1000}:${GID:-1000}"
    ports:
      - "8000:8000"
    volumes:
      - ${TEMPLATE_DIR:-./template}:/app/template
    environment:
      - ROOT_PATH=/app/template

  frontend:
    image: my-frontend
    build:
      context: ./file-editor/frontend
    ports:
      - "3000:3000"
    environment:
      - DATA_TYPES=${EDITOR_DATA_TYPES:-}
      - ITEM_DATA_TYPES=${EDITOR_ITEM_DATA_TYPES:-}
      - DEFAULT_PLUGINS=${EDITOR_DEFAULT_PLUGINS:-}
    depends_on:
      - backend
