# ==========================================
# cilium network cluster configuration
# ==========================================
cilium_network_cluster:
  # cluster region
  region: tw
  # cluster virtual ip cidr
  vip: 172.168.0.0/16
  # fabric variables dynamic object
  fab_vars: 'f12'
