# ==========================================
# should enable trident ssd
# ==========================================
trident_ssd: false # <=== [Override]


# ==========================================
# multitenant must using id=1, vip=192.168.1.1
# ==========================================
trident_ssd_object_ids:
- id: 1
  vip: 192.168.1.1/16
