# ==========================================
# Location of the fab
# ==========================================
fab_location: "tvm"


# ==========================================
# Location of the multitenant fab
# ==========================================
tvm_fabvar: "tvm"
