# ==========================================
# cilium network cluster configuration
# ==========================================
cilium_network_cluster:
  # cluster region
  region: 200mm-tvm
  # cluster virtual ip cidr
  vip: "172.168.0.0/16"
  # fabric variables dynamic object
  fab_vars: "{FAB}"
  # cilium global settings
  global: tvm
