# ==========================================
# Enable networking
# ==========================================
network_enabled: true


# ==========================================
# List of DNS servers
# ==========================================
dns_servers: # <=== [Override]
- "8.8.8.8"
- "8.8.4.4"
